# Generated by Django 2.2.4 on 2019-08-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(max_length=200)),
                ('sent_from', models.CharField(max_length=200)),
                ('send_date', models.DateTimeField(verbose_name='date published')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('archived', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
